services:
  app:
    build:
      context: ./polybot
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python -m polybot.bot

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8002:8002"


