version: '3.8'

services:
  app:
    build:
      context: ./polybot
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8001:8001"